config/routes.rb
FactualApi::Application.routes.draw do

  match "/show_details/:id"=>"searches#show_details" , :via=>[:get]
  match "/create_comment"=>"searches#create_comment" , :via=>[:post]
  match "/show/:search_category/:search_business/:city/:locality" => "searches#show" , :via=>[:get,:post]
  match "search_by_choice" => "searches#search_by_choice" , :via=>[:post]
  match "/search_text" => "searches#search_text" , :via=>[:get]
  root "searches#search_text"
end

app/models/category.rb
class Category < ActiveRecord::Base


end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true
  validates :comment , :presence=>true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/factual_data.rb
class FactualData < ActiveRecord::Base
  acts_as_commentable
  
  def self.dump_data(search_result)
    search_result = search_result.first
    factual_data =FactualData.where(
      :name=>search_result["name"],
      :address=>search_result["address"],
      :locality=>search_result["locality"],
      :country=>search_result["country"],
      :website=>search_result["website"],
      :postal_code=>search_result["postcode"]
    ).first_or_initialize
    factual_data.save
    search_result["category_labels"].flatten.each do |category|
      category= Category.where(
        :category_labels=>category,
        :factual_data_id=>factual_data.id
      ).first_or_initialize
      category.save
    end
    factual_data.id
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  KEY ="Ghxweml2HGOWSuuuCRl6FYkwvm4J3QTcZBx7Ydvb"
  SECRET= "PUPJLBmCXLPWLl2Gzwpipsd0vr2qdaoNkajMjOUs"


  #--
  # To create comment
  #++
  def create_comment
    factual_data=FactualData.find(params[:id])
    comment =  factual_data.comments.create
    comment.title = factual_data.name
    comment.comment = params[:comment]
    success = comment.save
    flash[:notice]= comment.errors.full_messages.first unless success
    redirect_to :action=>"show_details" , :id=>factual_data.id  
  end

  #--
  # To show business and comments
  #++
  def show_details
    @search_result=FactualData.find(params[:id])
    @comments = @search_result.comments.recent
  end


  #--
  # To show search result
  #++
  def show
    factual = call_factual()
    if params[:search_category].present? &&  params[:search_business].present?
      @search_result= factual.table("places").filters("$and"=>[{"category_labels"=>{"$includes_any"=>[params[:search_category]]}},{"name"=>params[:search_business]},{"locality"=>params[:locality]},{"postcode"=>params[:city]}]).rows
      @id = FactualData.dump_data(@search_result)
      flash[:notice]= ""
    else
      flash[:notice]= "No Result Found"
    end
  end

  #--
  # To display search result
  #++
  def search_by_choice  
    if params[:city].present?
      factual = call_factual()
      if params[:search_category].present? &&  params[:search_business].present?
        @search_result= factual.table("places").filters("$and"=>[{"category_labels"=>{"$includes_any"=>[params[:search_category]]}},{"name"=>params[:search_business]}],"$or"=>[{"locality"=>params[:city]},{"postcode"=>params[:city]}]).rows
       
        flash[:notice]= ""
      elsif params[:search_category].present?
        @search_result= factual.table("places").filters("category_labels"=>{"$includes_any"=>[params[:search_category]]},"$or"=>[{"locality"=>params[:city]},{"postcode"=>params[:city]}]).rows
        flash[:notice]= ""
      elsif params[:search_business].present? 
        @search_result= factual.table("places").filters("name"=> params[:search_business],"$or"=>[{"locality"=>params[:city]},{"postcode"=>params[:city]}]).rows
        flash[:notice]= ""
      else
        flash[:notice]= "Please enter Category name or Business name"
      end
    else
      flash[:notice]= "Please enter city or zip code"
    end
  end

  #--
  # To call factual
  #++

  def call_factual()
    require 'factual'
    return Factual.new(KEY, SECRET)
  end
  
  def search_text
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def request_by_search_by_choice(request)
    request == "search_by_choice"
  end

  def categories(factual_data)
    Category.where(:factual_data_id=>factual_data.id)
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FactualApi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/searches/_create_comment.html.erb
<%= form_tag "/create_comment" do %>
  <%= text_area_tag "comment" ,nil, :placeholder=>"Enter comment here" %>
  <%= hidden_field_tag "id", locals[:id] %><br/>
  <%= submit_tag "Add Comment" %>
<% end %>

app/views/searches/_display.html.erb
<% if @search_result.present? %>
  <% @search_result.each do |search| %>
    <b>Name</b> <%= search["name"] %><br>
    <b>Address</b> <%= search["address"] %><br/>
    <b>Locality</b> <%= search["locality"] %><br/>
    <b>Country</b> <%= search["country"] %><br/>
    <b> Website </b><%= link_to search["name"],search["website"] %><br/>
    <b>Post Code</b> <%= search["postcode"] %><br/>
    <b> Categories </b><% search["category_labels"].flatten.each do |category| %>
      <%= category %><br/>
    <% end %>
    <% if request_by_search_by_choice(params[:action]) %>
      <%= link_to "Show Details" , "/show/#{search["category_labels"].flatten.last}/#{search["name"]}/#{search["postcode"]}/#{search["locality"]}"%>
    <% end %>
    <br/>
    <br/><br/>
    <br/>
    <br/>

  <% end %>
<% else %>
  <%= flash[:notice] if flash[:notice].present? %>
  <%= "No Result found " if flash[:notice].blank?  %>
<% end %>

app/views/searches/_display_comments.html.erb
<b>Comments:</b>
<br/>
<%  unless @comments.blank? %>
  <% @comments.each do |comment| %>
    <div style="border-style:solid;border-width:medium;border-color:#98bf21;margin-top:5px;">
      <%= comment.comment %><br/><br/><br/>
    </div>
  <% end %>
<% else %>
  No Comment Yet
<% end %>

app/views/searches/search_by_choice.html.erb
<%= render "display" %>

app/views/searches/search_text.html.erb
<%= form_tag search_by_choice_path  do %>
  Search by category <%= text_field_tag  "search_category" %><br/>
  Search by buisness <%= text_field_tag  "search_business" %><br/>
  Search By City or Zip Code <%= text_field_tag "city" %><br/>
  <%= submit_tag "Search"  %>
<% end %>

app/views/searches/show.html.erb
<%= render "display" %>
<hr/>
<%= render "create_comment" , :locals=>{:id => @id} %>

app/views/searches/show_details.html.erb
<h4><%= flash[:notice] if flash[:notice].present? %> </h4>
<br/>
<% search = @search_result %>
<b>Name</b> <%= search.name %><br>
<b>Address</b> <%= search.address %><br/>
<b>Locality</b> <%= search.locality %><br/>
<b>Country</b> <%= search.country %><br/>
<b> Website </b><%= link_to search.name,search.website %><br/>
<b>Post Code</b> <%= search.postal_code %><br/>
<b> Categories </b><% categories(search).flatten.each do |category| %>
  <%= category.category_labels %><br/>
<% end %>
<br/>
<br/>
<hr/>
<%= render "create_comment" , :locals=>{:id => search.id}%>
<hr/>
<%= render "display_comments" %>
<br/>
<%= link_to "Back" ,root_url %>